import type { PublicActivity } from './types';

// Activity-only records are already reduced to their public projection here.
export const activities: PublicActivity[] = [
  {
    id: 'supervisor-meeting-2026-08-26',
    date: '2026-08-26',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-08-11',
    date: '2026-08-11',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'hci-research-presentation-2026-08-05-3',
    date: '2026-08-05',
    type: 'RESEARCH_GROUP_MEETING',
    visibility: 'PUBLIC',
    publicTitle: 'HCI Research Presentation & Lab Collaboration',
    publicSummary:
      'Discussed computational modelling in HCI and opportunities for interdisciplinary research collaboration.',
    topics: ['Human–Computer Interaction', 'Computational Modelling'],
  },
  {
    id: 'ai-transparency-discussion-2026-08-05-2',
    date: '2026-08-05',
    type: 'GROUP_READING',
    visibility: 'PUBLIC',
    publicTitle: 'AI Transparency, Autonomy & Trust Calibration',
    publicSummary:
      'Examined how AI transparency can improve trust calibration while also affecting user autonomy, cognitive load, and decision-making.',
    topics: ['AI Transparency', 'Human–AI Interaction', 'Trust Calibration'],
  },
  {
    id: 'hcii-conference-recap-2026-08-05-1',
    date: '2026-08-05',
    type: 'RESEARCH_GROUP_MEETING',
    visibility: 'PUBLIC',
    publicTitle: 'HCII Montreal Conference Recap & Paper Discussion',
    publicSummary:
      'Reflected on HCII conference themes spanning AI safety, explainability, ethics, privacy, and agent-based modelling.',
    topics: ['Human–Computer Interaction', 'AI Safety', 'Agent-Based Modelling'],
  },
  {
    id: 'supervisor-meeting-2026-07-31-2',
    date: '2026-07-31',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-31-1',
    date: '2026-07-31',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-24',
    date: '2026-07-24',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-14-2',
    date: '2026-07-14',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-14-1',
    date: '2026-07-14',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-10-2',
    date: '2026-07-10',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-10-1',
    date: '2026-07-10',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-08-2',
    date: '2026-07-08',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
  {
    id: 'supervisor-meeting-2026-07-08-1',
    date: '2026-07-08',
    type: 'SUPERVISOR_MEETING',
    visibility: 'ACTIVITY_ONLY',
    publicTitle: 'Supervisor Research Meeting',
    publicSummary: 'Research discussion · Private',
  },
];
